name: quinot
description: A quick note taking app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  path_provider: ^1.6.11
  path: ^1.7.0
  sqflite: ^1.3.1
  intl: ^0.16.1
  flutter_sqflite_manager: ^0.1.2
  connectivity: ^0.4.9
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_user.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 700

  
